# database-secret.yaml
apiVersion: v1
kind: Secret # Defines the type of Kubernetes resource as a Secret
metadata:
  name: my-database-credentials # The name of your Secret.
  namespace: my-app-dev # Specifies the namespace where this Secret will reside.
type: Opaque # The type of Secret. 'Opaque' is the default for arbitrary user-defined data.
             # Other types exist for specific uses (e.g., 'kubernetes.io/dockerconfigjson' for image pull secrets).
stringData: # Use 'stringData' for convenience. Kubernetes will automatically base64-encode these values.
            # Alternatively, you can use 'data' and provide base64-encoded values yourself.
  username: "dbuser" # The key for the username.
  password: "supersecretpassword123" # The key for the password.
  # Best practice: Do NOT put actual sensitive data directly in your Git repository.
  # Use CI/CD pipelines to inject these values securely or use external secret management systems.