# 05-greet-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-service-deployment
  namespace: my-realistic-app
  labels:
    app: greet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greet-service
  template:
    metadata:
      labels:
        app: greet-service
    spec:
      containers:
      - name: greet-app-container
        image: greet-service:1.0 # CHANGED: Image path for direct Kind load
        ports:
        - containerPort: 5000
        env:
        - name: GREET_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: greet-service-config
              key: greet_message