# 07-frontend-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html # Name of the ConfigMap
  namespace: my-realistic-app
data:
  index.html: | # The key 'index.html' will be the filename when mounted
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Kubernetes POC Frontend</title>
        <style>
            body { font-family: sans-serif; margin: 40px; background-color: #f0f2f5; color: #333; }
            .container { max-width: 800px; margin: 0 auto; background-color: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
            h1 { color: #2c3e50; text-align: center; margin-bottom: 30px;}
            .section { margin-bottom: 20px; padding: 15px; border: 1px solid #ddd; border-radius: 4px; background-color: #f9f9f9; }
            button {
                padding: 10px 20px;
                font-size: 16px;
                cursor: pointer;
                border: none;
                border-radius: 5px;
                margin-right: 10px;
                background-color: #3498db;
                color: white;
                transition: background-color 0.3s ease;
            }
            button:hover { background-color: #2980b9; }
            .response { margin-top: 10px; padding: 10px; border: 1px solid #eee; background-color: #e9e9e9; border-radius: 4px; }
            .error { color: red; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Kubernetes POC Frontend</h1>

            <div class="section">
                <h2>Hello Service</h2>
                <button onclick="fetchHello()">Get Hello Message</button>
                <div id="helloResponse" class="response"></div>
            </div>

            <div class="section">
                <h2>Greet Service</h2>
                <button onclick="fetchGreet()">Get Greet Message</button>
                <div id="greetResponse" class="response"></div>
            </div>
        </div>

        <script>
            // These paths are relative because Ingress handles the routing
            const HELLO_API_PATH = '/api/hello';
            const GREET_API_PATH = '/api/greet';

            async function fetchHello() {
                const responseDiv = document.getElementById('helloResponse');
                responseDiv.textContent = 'Loading...';
                try {
                    const response = await fetch(HELLO_API_PATH);
                    if (!response.ok) {
                        throw new Error(`HTTP error! status: ${response.status}`);
                    }
                    const data = await response.text(); // Assuming text response from Flask
                    responseDiv.textContent = `Response: "${data}"`;
                    responseDiv.classList.remove('error');
                } catch (error) {
                    responseDiv.textContent = `Error: ${error.message}. Check browser console for details.`;
                    responseDiv.classList.add('error');
                    console.error('Fetch Hello Error:', error);
                }
            }

            async function fetchGreet() {
                const responseDiv = document.getElementById('greetResponse');
                responseDiv.textContent = 'Loading...';
                try {
                    const response = await fetch(GREET_API_PATH);
                    if (!response.ok) {
                        throw new Error(`HTTP error! status: ${response.status}`);
                    }
                    const data = await response.text(); // Assuming text response from Flask
                    responseDiv.textContent = `Response: "${data}"`;
                    responseDiv.classList.remove('error');
                } catch (error) {
                    responseDiv.textContent = `Error: ${error.message}. Check browser console for details.`;
                    responseDiv.classList.add('error');
                    console.error('Fetch Greet Error:', error);
                }
            }
        </script>
    </body>
    </html>