# demo-project-2/kubernetes/01-db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials # Name of the secret
  namespace: demo-project-2-ns # Must be in the same namespace
type: Opaque # A general purpose secret type
data:
  # Base64 encoded values for username and password
  # 'admin' -> YWRtaW4=
  # 'dbpassword' -> ZGJwYXNzd29yZA==
  username: YWRtaW4= # echo -n "admin" | base64
  password: ZGJwYXNzd29yZA== # echo -n "dbpassword" | base64