# demo-project-2/kubernetes/10-backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: chatbot-backend-clusterip # Internal DNS name for the backend
  namespace: demo-project-2-ns
spec:
  selector:
    app: chatbot-backend # Matches the backend deployment pods
  ports:
    - protocol: TCP
      port: 80 # Service port (frontend will call /api/chat which ingress maps to /chat on backend)
      targetPort: 5000 # Target container port (Flask app's port)
  type: ClusterIP