# demo-project-2/kubernetes/14-ingress.yaml
apiVersion: networking.k8s.io/v1 # Ingress API version
kind: Ingress # Type of Kubernetes resource
metadata:
  name: chatbot-app-ingress # Name of the Ingress resource
  namespace: demo-project-2-ns
  annotations:
    # This annotation is crucial for path rewriting with Nginx Ingress Controller.
    # It tells the controller to rewrite the URI that is sent to the backend.
    # The value /$1 means that the matched group from the regex (everything after the /api/)
    # will be used as the new target path.
    nginx.ingress.kubernetes.io/rewrite-target: /$1

    # This annotation enables regex support for the paths defined below.
    # It's needed when using capture groups for rewrite-target.
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx # Specifies which Ingress Controller will handle this Ingress
  rules:
  - http:
      paths:
      # Rule for the Frontend UI: serves content at the root path '/'
      - path: / # Matches the root path
        pathType: Prefix
        backend:
          service:
            name: chatbot-frontend-clusterip # Directs traffic to the frontend service
            port:
              number: 80

      # Rule for Chatbot Backend API: routes /api/chat to the backend service.
      # The regex (chat.*) captures 'chat' and any subpath, making it $1.
      # This ensures the backend Flask app receives '/chat' (or /chat/subpath) as its route.
      - path: /api/(chat.*) # Matches /api/chat and any subpath
        pathType: Prefix
        backend:
          service:
            name: chatbot-backend-clusterip # Directs traffic to the backend service
            port:
              number: 80